config/routes.rb
TicketShop::Application.routes.draw do
  devise_for :users
  root "products#index"
  resources :products, only: [:index, :show]
  resources :charges, only: [:new, :create]
  post '/products/:product_id/add_to_cart', to: 'cart_items#create', as: 'add_product_to_cart'
  get '/cart', to: 'cart_items#index', as: 'cart'
  delete '/cart/:id', to: 'cart_items#delete', as: 'remove_product_from_cart'

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  belongs_to :charge
end

app/models/charge.rb
class Charge < ActiveRecord::Base
  has_many :cart_items 
  has_many :products, through: :cart_item
  has_one :user, through: :cart_items

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :users, through: :cart_items
 has_many :cart_items
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :cart_items
  has_many :products, through: :cart_items

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    product = Product.find(params[:product_id])
    cart_item = product.cart_items.build(user: current_user)
    cart_item.save
    redirect_to :cart
  end

  def index
     @cart_items = current_user.cart_items
  end

  def delete
    CartItem.find(params[:id]).destroy
    redirect_to :cart
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => 'example@stripe.com',
    :card  => params[:stripeToken]
    )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
    )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to charges_path
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    if params[:id]
    @product = Product.find(params[:id])
  end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/cart_items/index.html.erb
<% @cart_items.each do |item| %>
<div>
<%= item.product.name %>
<%= item.product.price %>
<%= button_to "remove from cart", remove_product_from_cart_path(item), method: :delete %>
</div>
<% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketShop</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "bootstrap-responsive.css" %>
  <%= stylesheet_link_tag "home" %>
  <%= javascript_include_tag "application" %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.3/angular.min.js"></script>
  <link rel="stylesheet" href="css/bootstrap.css"  type="text/css"/>
  <link rel="stylesheet" href="css/colors.css" />
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="js/bootstrap.js"></script>
  <script src="main.js"></script>
</head>
<body>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to "Shopping Cart", cart_path %>
  </li>
  <li>
  <%= link_to('Account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>



<div class="container-fluid">
    <div class="row-fluid">
      <div class="row-fluid" id="header-section">
      <div class='span9 main-content' id='page-content'>
        <h1>Bulk<span>Tix</span></h1>
        <h2>Bigger. Better. Stronger.</h2>
        <div class="shopping-cart"></div>
        <h5>showing theaters near hopkinton</h5>
        <div class="span4"></div> <!-- for centering zip code -->
        <div class="span4 search-field">
          <input type="text" placeholder="Enter Zip Code">
          <button type="submit" class="btn btn-info">Find Theaters</button>
        </div>

<%= yield %>

      </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/products/_login.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to "Shopping Cart", cart_path %>
  </li>
  <li>
  <%= link_to('Account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/products/_template.html.erb
<div class="container-fluid">
    <div class="row-fluid">
      <div class="row-fluid" id="header-section">
      <div class='span9 main-content' id='page-content'>
        <h1>Bulk<span>Tix</span></h1>
        <h2>Bigger. Better. Stronger.</h2>
        <div class="shopping-cart"></div>
        <h5>showing theaters near hopkinton</h5>
        <div class="span4"></div> <!-- for centering zip code -->
        <div class="span4 search-field">
          <input type="text" placeholder="Enter Zip Code">
          <button type="submit" class="btn btn-info">Find Theaters</button>
        </div>
        <div class='span9 main-content'>
        <div class="span4"></div> <!-- for centering zip code -->
        </div>
        <div class="row-fluid content-row">
          <div class="span12 ">
<!-- one list item -->
        <div class='span6 item'>
          <div class="span4">
            <div class='img-wrapper'>
              <img src="assets/amc_logo.jpg" id='amc-logo'>
            </div>
        
          </div>
          <div class="item-description">
            <div class='span8'>
                <div class='row-fluid tckt-option'>
                  <p class='span5 only-option'><a>&#9432;</a>Gold ticket</p>
                  <p class='amount span3'>$50.00</p>
                  <input type="text" class="quantity span4">
                </div>
                <div class='row-fluid tckt-option'>
                  <p class='span5'><a>&#9432;</a>Silver ticket</p>
                  <p class='amount span3'>$25.00</p>
                  <input type="text" class="quantity span4">
                </div>
                <div class='row-fluid centered-btn-wrapper'>
                  <div class="span5"></div>
                  <button type="submit" class="btn btn-info span5">update cart</button>
                  <div class="span4"></div>
                </div>
              </div>  <!-- span8 -->
            </div> <!-- item description -->
          </div>
<!-- end list item -->
<!--  second-item -->
            <div class='span6 item'>
              <div class="span4">
                <div class="img-wrapper">
                  <img src="assets/century_logo.jpg" class='theater-logo'>
                </div>
                <!-- <h5>AMC</h5> -->
              </div>
              <div class="item-description">
              <div class='span8'>
              
                  <div class='row-fluid'>
                    <p class='span5 only-option'><a>&#9432;</a>Gold ticket</p>
                    <p class='amount span3'>$50.00</p>
                    <input type="text" class="quantity span4">
                  </div>
                  <div class='row-fluid'>
                    <p class='span5 only-option'><a>&#9432;</a>Silver ticket</p>
                    <p class='amount span3'>$25.00</p>
                    <input type="text" class="quantity span4">
                  </div>
                  <div class='row-fluid'>
                    <div class="span4"></div>
                    <button type="submit" class="btn btn-info span5">update cart</button>
                    <div class="span4"></div>
                  </div>
          
            </div>  <!-- span8 -->
            </div> <!-- item description -->
            </div>
          <!--  end second item and first row-->
          </div>
        </div>

        <div class="row-fluid content-row">
          <div class="span12 ">
<!-- one list item -->
        <div class='span6 item'>
          <div class="span4">
            <div class='img-wrapper'>
              <img src="assets/cinema_de_lux_logo.gif" id='amc-logo'>
            </div>
                <!-- <h5>AMC</h5> -->
          </div>
          <div class="item-description">
            <div class='span8'>
                <div class='row-fluid tckt-option'>
                  <p class='span5 only-option'><a>&#9432;</a>Gold ticket</p>
                  <p class='amount span3'>$50.00</p>
                  <input type="text" class="quantity span4">
                </div>
                <div class='row-fluid tckt-option'>
                  <p class='span5'><a>&#9432;</a>Silver ticket</p>
                  <p class='amount span3'>$25.00</p>
                  <input type="text" class="quantity span4">
                </div>
                <div class='row-fluid centered-btn-wrapper'>
                  <div class="span4"></div>
                  <button type="submit" class="btn btn-info span5">update cart</button>
                  <div class="span4"></div>
                </div>
              </div>  <!-- span8 -->
            </div> <!-- item description -->
          </div>
<!-- end list item -->
<!--  second-item -->
            <div class='span6 item'>
              <div class="span4">
                <div class="img-wrapper">
                  <img src="assets/cinemark_logo.gif" class='theater-logo '>
                </div>
                <!-- <h5>AMC</h5> -->
              </div>
              <div class="item-description">
              <div class='span8'>
                <div class="option1">
                  <div class='row-fluid'>
                    <p class='span5 only-option'><a>&#9432;</a>Gold ticket</p>
                    <p class='amount span3'>$50.00</p>
                    <input type="text" class="quantity span4">
                  </div>
                  <div class='row-fluid'>
                    <p class='span5 only-option'><a>&#9432;</a>Silver ticket</p>
                    <p class='amount span3'>$25.00</p>
                    <input type="text" class="quantity span4">
                  </div>
                  <div class='row-fluid'>
                    <div class="span4"></div>
                    <button type="submit" class="btn btn-info span5">update cart</button>
                    <div class="span4"></div>
                  </div>
                </div>
            </div>  <!-- span8 -->
            </div> <!-- item description -->
            </div>
          <!--  end second item and first row-->
          </div>
        </div>
      </div>
    
      </div>
    </div>
  </div> 

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |product| %>
<div>
<%= product.company %>
<%= product.name %>
<%= number_to_currency product.price %>
<%#= truncate product.description, length: 100 %>
</div>

<%= button_to "Add Item to Cart", add_product_to_cart_path(product) %>
<% end %>